import type { Customer } from '@/types/customer';

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'cust-001',
    name: 'Marcus Rivera',
    company: 'Apex Logistics Group',
    email: 'marcus.rivera@apexlogistics.com',
    phone: '(512) 555-0142',
    tenureYears: 7,
    tier: 'Gold',
    healthScore: 82,
    billingStatus: 'Current',
    monthlyRevenue: 4850,
    accountManager: 'Sarah Chen',
    lastContactDate: '2024-05-28',
    location: {
      address: '1450 Commerce Park Dr',
      city: 'Austin',
      state: 'TX',
      zip: '78701',
      serviceZone: 'Central TX Metro',
    },
    services: [
      {
        id: 'svc-001',
        name: 'Enterprise Fiber 1Gbps',
        category: 'Internet',
        status: 'active',
        monthlyValue: 850,
      },
      {
        id: 'svc-002',
        name: 'Hosted PBX Pro (25 lines)',
        category: 'Voice',
        status: 'active',
        monthlyValue: 1200,
      },
      {
        id: 'svc-003',
        name: 'SD-WAN Managed',
        category: 'Network',
        status: 'active',
        monthlyValue: 1800,
      },
      {
        id: 'svc-004',
        name: 'Cloud Backup 10TB',
        category: 'Cloud',
        status: 'active',
        monthlyValue: 600,
      },
      {
        id: 'svc-005',
        name: 'DDoS Protection Premium',
        category: 'Security',
        status: 'available',
        monthlyValue: 400,
      },
      {
        id: 'svc-006',
        name: 'Enterprise Fiber 10Gbps',
        category: 'Internet',
        status: 'available',
        monthlyValue: 2200,
      },
      {
        id: 'svc-007',
        name: 'SIP Trunking (50 channels)',
        category: 'Voice',
        status: 'available',
        monthlyValue: 500,
      },
      {
        id: 'svc-008',
        name: 'Dark Fiber',
        category: 'Network',
        status: 'unavailable',
        monthlyValue: 0,
      },
    ],
    interactions: [
      {
        id: 'int-001',
        type: 'crm',
        date: '2024-05-28',
        agent: 'Sarah Chen',
        subject: 'Quarterly Business Review',
        summary:
          'Discussed expansion of network capacity. Marcus expressed interest in 10Gbps upgrade.',
        sentiment: 'positive',
        fullTranscript:
          'Call with Marcus Rivera, 45 minutes. Covered Q2 performance metrics — uptime 99.98%, no major incidents. Marcus flagged that their new Austin warehouse (opening Q4) will need fiber service. Showed strong interest in 10Gbps upgrade for head office when contract renews in January. Mentioned competitor (Spectrum Business) has been calling. Budget is approved for FY2025. Action: send 10Gbps quote by June 5.',
        tags: ['expansion', 'renewal', '10Gbps', 'competitive'],
      },
      {
        id: 'int-002',
        type: 'support',
        date: '2024-05-10',
        agent: 'NOC Team',
        subject: 'Intermittent packet loss on SD-WAN node',
        summary: 'Packet loss issue on Austin primary SD-WAN node resolved in 2h 15m.',
        sentiment: 'neutral',
        fullTranscript:
          'Ticket #TKT-88923. Marcus reported intermittent packet loss starting 09:14 CST. NOC identified misconfigured BGP peer on edge router AU-3. Rolled back config, issue resolved by 11:29 CST. Marcus satisfied with resolution time. MTTR: 2h 15m. SLA met (4h target). Root cause: change management gap during overnight maintenance window. Preventative action: add config validation check to change process.',
        tags: ['SD-WAN', 'packet-loss', 'resolved', 'SLA-met'],
      },
      {
        id: 'int-003',
        type: 'billing',
        date: '2024-04-22',
        agent: 'Billing Ops',
        subject: 'Invoice dispute — bandwidth overage charge',
        summary:
          'Customer disputed $340 overage charge. Credited after confirming measurement error.',
        sentiment: 'negative',
        fullTranscript:
          'Marcus called billing regarding April invoice. Disputed $340 overage charge on Enterprise Fiber. Customer pulled their own SNMP data showing they never exceeded committed rate. Billing ops reviewed measurement logs — confirmed metering script had a bug for the March 28 maintenance window, double-counting traffic during that 4-hour period. Issued full credit $340. Marcus was frustrated ("this is the second billing issue in 6 months") but accepted resolution. Flagged account for enhanced billing review.',
        tags: ['billing-dispute', 'credit-issued', 'measurement-error', 'at-risk'],
      },
      {
        id: 'int-004',
        type: 'marketing',
        date: '2024-04-01',
        agent: 'Marketing Automation',
        subject: 'DDoS Protection upgrade campaign — email opened',
        summary: 'Marcus opened DDoS Protection Premium offer email. Did not click CTA.',
        sentiment: 'neutral',
        fullTranscript:
          'Drip campaign: "Protect Your Business" — DDoS Protection Premium. Email delivered 04/01 08:05, opened 04/01 09:22 (Austin, Chrome). No link click recorded. Subject line: "Your current plan doesn\'t cover volumetric attacks — here\'s what Gold customers are adding." A/B variant B (ROI focus). Unsubscribe rate for campaign: 0.8%.',
        tags: ['DDoS', 'email', 'opened', 'no-click', 'upsell-candidate'],
      },
      {
        id: 'int-005',
        type: 'crm',
        date: '2024-03-15',
        agent: 'Sarah Chen',
        subject: 'Competitive threat — Spectrum Business quote shared',
        summary: 'Marcus shared Spectrum quote. $200/mo cheaper but no SD-WAN or managed services.',
        sentiment: 'negative',
        fullTranscript:
          "30-minute call. Marcus forwarded Spectrum Business proposal: 1Gbps fiber at $620/mo (vs our $850), includes basic router. No managed SD-WAN, no SLA above 99.9%, no 24/7 NOC. Discussed TCO — Spectrum quote doesn't include managed services or dedicated account team. Marcus acknowledged value but said CFO is pushing cost reduction. Sarah proposed a loyalty discount review if Marcus signs 3-year extension. Marcus said he'd think about it. Risk level: Medium. Next step: get approval for 10-15% loyalty discount.",
        tags: ['competitive', 'Spectrum', 'churn-risk', 'discount-needed'],
      },
      {
        id: 'int-006',
        type: 'support',
        date: '2024-02-28',
        agent: 'Tier 2 Support',
        subject: 'PBX softphone compatibility issue — Cisco Jabber',
        summary: 'Cisco Jabber calls dropping after 8 minutes. Resolved with SIP timer fix.',
        sentiment: 'neutral',
        fullTranscript:
          'Ticket #TKT-87201. 12 users reporting Cisco Jabber calls dropping after approximately 8 minutes. Tier 1 escalated after first-level reboot did not help. Tier 2 identified SIP session timer mismatch between Jabber client (default 1800s) and our PBX (480s). Updated session expires value on PBX config. Issue resolved, no recurrence in 72h monitoring window. MTTR: 1 day (due to Tier 1 escalation delay). Resolution note sent to customer.',
        tags: ['PBX', 'SIP', 'Jabber', 'resolved'],
      },
      {
        id: 'int-007',
        type: 'crm',
        date: '2024-01-08',
        agent: 'Sarah Chen',
        subject: 'Contract renewal — 2-year extension signed',
        summary: 'Marcus signed 2-year renewal with 5% rate lock. Added Cloud Backup to bundle.',
        sentiment: 'positive',
        fullTranscript:
          'Marcus signed 2-year renewal effective January 15. Contract includes: all existing services at 5% rate lock (waiving standard 3% annual increase), plus Cloud Backup 10TB added at $600/mo. Total MRR moves from $3,650 to $4,450. Marcus specifically mentioned the SD-WAN performance and dedicated NOC as reasons for renewing over competitor offers. Sent welcome gift (Yeti tumbler set). Flagged for executive check-in at 6-month mark.',
        tags: ['renewal', 'signed', '2-year', 'expansion', 'won'],
      },
    ],
  },
  {
    id: 'cust-003',
    name: 'Trevor Banks',
    company: 'FastShip Fulfillment Co.',
    email: 'tbanks@fastshipfulfillment.com',
    phone: '(214) 555-0399',
    tenureYears: 1,
    tier: 'Silver',
    healthScore: 43,
    billingStatus: 'Current',
    monthlyRevenue: 1650,
    accountManager: 'James Whitfield',
    lastContactDate: '2024-04-30',
    location: {
      address: '3300 Logistics Way',
      city: 'Dallas',
      state: 'TX',
      zip: '75247',
      serviceZone: 'DFW Industrial Corridor',
    },
    services: [
      {
        id: 'svc-201',
        name: 'Business Fiber 500Mbps',
        category: 'Internet',
        status: 'active',
        monthlyValue: 450,
      },
      {
        id: 'svc-202',
        name: 'IP Voice (10 lines)',
        category: 'Voice',
        status: 'active',
        monthlyValue: 500,
      },
      {
        id: 'svc-203',
        name: 'Business Fiber 1Gbps',
        category: 'Internet',
        status: 'available',
        monthlyValue: 750,
      },
      {
        id: 'svc-204',
        name: 'Cloud PBX (50 lines)',
        category: 'Voice',
        status: 'available',
        monthlyValue: 800,
      },
      {
        id: 'svc-205',
        name: 'Business Cloud Backup 2TB',
        category: 'Cloud',
        status: 'available',
        monthlyValue: 200,
      },
      {
        id: 'svc-206',
        name: 'SD-WAN Starter',
        category: 'Network',
        status: 'available',
        monthlyValue: 350,
      },
      { id: 'svc-207', name: 'MPLS', category: 'Network', status: 'unavailable', monthlyValue: 0 },
    ],
    interactions: [
      {
        id: 'int-201',
        type: 'crm',
        date: '2024-04-30',
        agent: 'James Whitfield',
        subject: '6-month check-in call',
        summary:
          'Trevor mentioned internet is "too slow during peak hours." Competitor AT&T Fiber is being evaluated.',
        sentiment: 'negative',
        fullTranscript:
          "20-minute call. Trevor reports that 500Mbps is consistently saturated between 12-2pm and 6-8pm when their shipping sorters and barcode scanners all run simultaneously. He's frustrated — says he mentioned bandwidth needs during sales cycle but was told 500Mbps would be sufficient. AT&T Fiber called him last week offering 1Gbps at $680/mo (includes install). Our 1Gbps is $750. Trevor feels he was undersold. James acknowledged the frustration and offered to run a bandwidth analysis. Trevor agreed to a 30-day monitoring period before making a decision. Risk: HIGH.",
        tags: ['bandwidth', 'undersold', 'at-risk', 'competitive', 'AT&T'],
      },
      {
        id: 'int-202',
        type: 'support',
        date: '2024-04-15',
        agent: 'Tier 1 Support',
        subject: 'Internet slowness complaint — 3rd ticket in 60 days',
        summary: '3rd bandwidth complaint this year. Customer very dissatisfied.',
        sentiment: 'negative',
        fullTranscript:
          'Ticket #TKT-91204. Trevor called again about slowness. Previous tickets: #TKT-88001 (Feb 12) and #TKT-89441 (Mar 28). Each time, utilization shows 95%+ during business hours. Tier 1 advised on QoS settings — customer already has QoS enabled. No resolution possible without bandwidth upgrade. Flagged to account manager. Trevor said "if this keeps happening I\'m going to have to look at other options." CSAT score: 1/5.',
        tags: ['bandwidth', 'repeat-ticket', 'CSAT-1', 'churn-risk'],
      },
      {
        id: 'int-203',
        type: 'crm',
        date: '2024-03-05',
        agent: 'James Whitfield',
        subject: 'New contract signed — onboarding complete',
        summary: 'Trevor joined 12 months ago. Initial onboarding completed successfully.',
        sentiment: 'positive',
        fullTranscript:
          "Onboarding complete confirmation. Business Fiber 500Mbps and IP Voice 10 lines live. Trevor happy with installation team (gave installer 5 stars). Service provisioned on schedule. Welcome call went well — Trevor's main use case: warehouse management system, 25 barcode scanners, VOIP for 10 dispatchers. Recommended 500Mbps as adequate for stated needs. (Note: Trevor mentioned plans to add 10 more scanners in Q3 — this was flagged in CRM but not escalated for upsell review.)",
        tags: ['onboarding', 'new-customer', 'warehouse', 'growth-signal-missed'],
      },
    ],
  },
  {
    id: 'cust-004',
    name: 'Linda Marchetti',
    company: 'Marchetti Law Group',
    email: 'lmarchetti@marchettilaw.com',
    phone: '(210) 555-0051',
    tenureYears: 11,
    tier: 'Silver',
    healthScore: 91,
    billingStatus: 'Current',
    monthlyRevenue: 980,
    accountManager: 'Sarah Chen',
    lastContactDate: '2024-05-20',
    location: {
      address: '200 W Commerce St, Suite 1800',
      city: 'San Antonio',
      state: 'TX',
      zip: '78205',
      serviceZone: 'San Antonio CBD',
    },
    services: [
      {
        id: 'svc-301',
        name: 'Business Fiber 250Mbps',
        category: 'Internet',
        status: 'active',
        monthlyValue: 280,
      },
      {
        id: 'svc-302',
        name: 'Hosted PBX (8 lines)',
        category: 'Voice',
        status: 'active',
        monthlyValue: 420,
      },
      {
        id: 'svc-303',
        name: 'Business Fiber 500Mbps',
        category: 'Internet',
        status: 'available',
        monthlyValue: 380,
      },
      {
        id: 'svc-304',
        name: 'Legal Cloud Storage (FIPS 140-2)',
        category: 'Cloud',
        status: 'available',
        monthlyValue: 350,
      },
      {
        id: 'svc-305',
        name: 'Secure Fax-to-Email',
        category: 'Voice',
        status: 'available',
        monthlyValue: 60,
      },
    ],
    interactions: [
      {
        id: 'int-301',
        type: 'crm',
        date: '2024-05-20',
        agent: 'Sarah Chen',
        subject: 'Annual review — very satisfied, loyalty discussion',
        summary:
          "Linda is delighted with service. Hasn't thought about alternatives in years. Great referral candidate.",
        sentiment: 'positive',
        fullTranscript:
          "25-minute call with Linda and office manager Patricia Nguyen. Linda has been a customer for 11 years — says she hasn't had a single billing issue and the internet has \"never gone down that I noticed.\" Celebrates our responsive tech support. Mentioned that two other law firms in her building (Floors 12 and 14) have asked her about her ISP. She's referred us informally before but doesn't know if we have a referral program. Patricia asked about FIPS-compliant cloud storage for client case files — they're being audited and need to store confidential materials off-site. This is a clear upsell and referral opportunity.",
        tags: ['loyal', 'satisfied', 'referral-candidate', 'cloud-storage-interest', 'upsell'],
      },
      {
        id: 'int-302',
        type: 'support',
        date: '2024-02-09',
        agent: 'Tier 1 Support',
        subject: 'VoIP echo on conference calls',
        summary: 'Echo on PBX conference bridge resolved by updating echo cancellation firmware.',
        sentiment: 'positive',
        fullTranscript:
          'Ticket #TKT-84501. Linda reported echo on conference bridge calls (only when 4+ participants). Tier 1 identified outdated firmware on conference bridge module — echo cancellation algorithm improvement in newer version. Updated firmware during after-hours maintenance window as requested. Linda sent thank-you email the next morning.',
        tags: ['PBX', 'echo', 'resolved', 'positive-feedback'],
      },
      {
        id: 'int-303',
        type: 'marketing',
        date: '2024-01-15',
        agent: 'Marketing Automation',
        subject: 'Referral program email — opened and forwarded',
        summary: 'Linda opened referral program email and forwarded it to a contact (tracked).',
        sentiment: 'positive',
        fullTranscript:
          'Referral program campaign: "Earn $200 for every business you refer." Email delivered 01/15. Linda opened 01/15 at 11:03am and forwarded to one external contact (email domain: garza-associates.com) at 11:08am. No referral completed yet — forward recipient did not click. High-quality warm lead if followed up. Linda is clearly our best advocate in the SA CBD market.',
        tags: ['referral', 'forwarded', 'warm-lead', 'advocate'],
      },
    ],
  },
  {
    id: 'cust-005',
    name: 'Ray Calloway',
    company: 'Calloway Auto Group',
    email: 'rcalloway@callowayauto.com',
    phone: '(469) 555-0715',
    tenureYears: 2,
    tier: 'Bronze',
    healthScore: 29,
    billingStatus: 'Collections',
    monthlyRevenue: 620,
    accountManager: 'James Whitfield',
    lastContactDate: '2024-04-02',
    location: {
      address: '4500 Auto Mile Blvd',
      city: 'Plano',
      state: 'TX',
      zip: '75093',
      serviceZone: 'DFW North',
    },
    services: [
      {
        id: 'svc-401',
        name: 'Business Cable 200Mbps',
        category: 'Internet',
        status: 'active',
        monthlyValue: 180,
      },
      {
        id: 'svc-402',
        name: 'IP Voice (5 lines)',
        category: 'Voice',
        status: 'active',
        monthlyValue: 250,
      },
      {
        id: 'svc-403',
        name: 'Business Fiber (when available)',
        category: 'Internet',
        status: 'unavailable',
        monthlyValue: 0,
      },
    ],
    interactions: [
      {
        id: 'int-401',
        type: 'billing',
        date: '2024-04-02',
        agent: 'Collections',
        subject: 'Account sent to collections — 90 days overdue',
        summary:
          'Three invoices ($620 × 3 = $1,860) unpaid. Account escalated to collections team.',
        sentiment: 'negative',
        fullTranscript:
          'Account escalated to collections after 3 failed payment attempts. Feb, Mar, Apr invoices all unpaid ($1,860 total). Ray has not responded to 4 emails, 2 voicemails, or 1 certified letter. Collections team sent formal notice. Service suspension scheduled for April 15 if no payment. Last known contact: Ray\'s assistant said "Ray is dealing with a personal matter and will call back." No callback received.',
        tags: ['collections', 'overdue-90-days', 'no-response', 'suspension-pending'],
      },
      {
        id: 'int-402',
        type: 'crm',
        date: '2024-02-20',
        agent: 'James Whitfield',
        subject: 'Check-in call — account deteriorating',
        summary:
          'Ray mentioned cash flow issues after key salesperson departure. Asked for payment plan.',
        sentiment: 'negative',
        fullTranscript:
          '15-minute call. Ray answered, explained that their top salesperson left in December and took 3 accounts with him. Revenue is down ~30% this quarter. Asked if we could do a 60-day payment deferral or payment plan. James offered a 30-day extension and a payment plan (split into 3 installments). Ray agreed verbally but did not sign the payment plan form sent by email. January invoice was also not paid. James noted Ray seems distressed — not a deliberate non-payer, but a genuine business hardship.',
        tags: ['payment-plan', 'cash-flow', 'hardship', 'verbal-agreement'],
      },
      {
        id: 'int-403',
        type: 'support',
        date: '2024-01-10',
        agent: 'Tier 1 Support',
        subject: 'VOIP calls dropping — showroom floor',
        summary: 'IP Voice calls dropping on showroom extension. Resolved — defective handset.',
        sentiment: 'neutral',
        fullTranscript:
          'Ticket #TKT-87801. Calls dropping on showroom phone (ext 105) after 2-3 minutes. Tier 1 dispatched technician. Found defective Polycom VVX 401 handset — phone swap resolved issue within 24 hours. Ray sent text to James: "thanks for the fast fix." No other issues noted at this time.',
        tags: ['VOIP', 'handset', 'resolved', 'positive-feedback'],
      },
    ],
  },
];

export function getCustomerById(id: string): Customer | undefined {
  return MOCK_CUSTOMERS.find((c) => c.id === id);
}
